steps:
  - command: .buildkite/scripts/run_autoformat.py
    label: "autoformat"

  - label: "test edge_lambdas"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: edge_lambdas
          command: ["yarn", "test"]

  - label: "deploy edge_lambdas"
    branches: "master"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: edge_lambdas
          command: [ "yarn", "deploy" ]
